version: 2
jobs:
 build:
   docker:
     - image: circleci/golang:1.13.4-buster
   steps:
     - checkout
     - setup_remote_docker:
        docker_layer_caching: false
        version: 18.06.0-ce
     - run:
         name: Print working dir
         command: pwd
     - run:
         name: List files
         command: ls -lah
     - run:
         name: Check env vars
         command: env
     - run:
         name: Build docker image
         command: docker build -t "jodybro/${CIRCLE_PROJECT_REPONAME}:v0.1.${CIRCLE_BUILD_NUM}" .
     - run:
         name: Log into docker hub
         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run:
         name: Push image to docker hub
         command: docker push "jodybro/${CIRCLE_PROJECT_REPONAME}:v0.1.${CIRCLE_BUILD_NUM}"

workflows:
    version: 2
    build_and_push:
        jobs:
            - build
